# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    backend:
      name: Backend Tests
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Setup Python & dependencies
          run: |
            cd backend
            python -m pip install --upgrade pip
            pip install poetry
            # Remova qualquer config que desative o venv:
            # poetry config virtualenvs.create false
            poetry install --no-interaction --no-ansi --no-root

        - name: Run backend tests
          run: |
            cd backend
            poetry run pytest --maxfail=1

