jobs:
  backend:
    name: Backend Tests
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: test-secret-key
      DATABASE_URL: "sqlite:///:memory:"

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python & dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction --no-ansi --no-root

      - name: Run backend tests
        run: |
          cd backend
          poetry run pytest --maxfail=1
