# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi

      - name: Run backend tests
        working-directory: backend
        run: poetry run pytest --maxfail=1 --disable-warnings -q

      - name: Lint with flake8
        working-directory: backend
        run: |
          poetry run flake8 .

  # você pode adicionar um job frontend aqui, por ex. ESLint/Prettier
  # ou remover se preferir focar no backend
